[package]
  cjc-version = "1.0.3"
  compile-option = "--experimental --enable-eh -Woff unused"
  description = ""
  name = "cangjie_experiments"
  output-type = "executable"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  [package.package_configuration]
  [package.scripts]

[target.aarch64-apple-darwin.bin-dependencies]
  path-option = ["${CANGJIE_STDX_PATH}"]
[target.x86_64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${CANGJIE_STDX_PATH}"]
[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["${CANGJIE_STDX_PATH}"]
